[package]
name = "rlox"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.1.0"
phf = { version = "0.11.2", features = ["macros"] }

[dev-dependencies]
assert_cmd = "2.0.12"
claim = "0.5.0"
predicates = "3.0.4"
